export * from "./windows";
export * from "./about/AboutDialog";
export * from "./color/ColorDialog";
export * from "./edit/edit-data/EditDataDialog";
export * from "./edit/edit-diagram/EditDiagramDialog";
export * from "./export/ExportDialog";
export * from "./link/LinkDialog";
export * from "./open/OpenDialog";
export * from "./textarea/TextareaDialog";
